# Welcome to abaekili's website!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: akili-online
email: abaeakili254@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just like the gazelle in the African savannah; 
  it has to wake up everyday knowing that it must be fast enough to outwit the fastest cheetah
  or it might be eaten, the same goes to the cheetah, or it might starve to death.
  Everyday, we are in a hurry, it doesnt matter if you are the cheetah, or the gazelle but
  you must be the best!
  Welcome to mysite! Happy Exploring!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: abaeakili
github_username:  abaeakili

# Build settings
markdown: kramdown
