# Welcome to abaekili's website!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: akili-online
email: abaeakili254@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Abae is a Website & Mobile Application developer.
  Business Management & Computer Science student.
  An Entrepreneur, Environmentalist & I love travelling.
  I live in the Coastal City of Mombasa, Kenya.
  I love Creating Stuff, playing with Electronics & reading Blogs.
  I enjoy spending time with my Friends and Family,
  & when I am not with them, then I am Sharing Knowledge...
  or learning a new thing with the Tech Community here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: abaeakili
github_username:  abaeakili

# Build settings
markdown: kramdown
